### ISSUE TITLE
Finished trick not shown for long enough before it is taken by the winner

### ISSUE THREAD

**Issue by wheelerlaw** [Rescator7/Hearts#3]
Pretty self explanatory. When a trick is completed, but before it has been taken by the winner, it would be nice if there was a second or two where it was still visible like in a real game. Right now, the finished trick is collected VERY quickly, so little to no ability to see the cards that were played.

**Comment by Rescator7** [comment]
There is a small delay (less than half a second).

I'm not sure 1 or 2 second(s) delay at the end of a Trick would be great, because game will be so slow... It's hard to have the "perfect" delay, to let see cards, but at the same time avoid slowing down the game too much...
hmm. Unless, i raise it more, but only for game speed "slow"... ?

------------------------------------------------------------------------------------------------------------------------------

Otherwise, it's possible to tune your own version of the game.

It's defined in the file config.h

The constant "SPEED_CLEAR_TABLE_VALUES" contain the delay value in ms (millisecond eg: 1000ms = 1 second) (delay before we clear the table at the end of a trick)

const int SPEED_CLEAR_TABLE_VALUES[3]    = {350, 200, 100};

First value 350 is the delay for "slow game speed" = 350 ms
Second value 200 is the delay for "normal game speed" = 200 ms
Third value 100 is the delay for "fast game speed" = 100 ms

For e.g: Those values could be raised to 1000 or above to have 1 second delay.

**Comment by Rescator7** [comment]
I got an idea. Along with the build-in speeds (normal, fast, and slow). I'll create an expert (speed mode) where it will be possible to tune-up all the games delays... from 0 to 3000 ms using side bars. So, let's says someone want a 2 seconds delay at the end of the tricks. It will be possible in the expert mode. (not as user-friendly as using build-in speed, but still useful to expert). It's going to takes sometimes to finish the code. I'll close this issue once it will be done.

**Comment by Rescator7** [comment]
version 1.8.10

menu settings->Game_speed->customized (Expert)
Adjust "Clear table" to 1000 or 1500
and click "Save"
